# Generated by Django 4.0.3 on 2022-04-14 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.class'),
        ),
    ]
