# Generated by Django 4.0.3 on 2022-04-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_teacher_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sid',
            new_name='mob',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='uid',
            new_name='mob',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='tid',
        ),
    ]
